"namespace MyApp {"
"public class HelloITI { public void printHelloITI() { Console.WriteLine(\"Hello ITI\"); } }" 
"public void printHelloGit() { Console.WriteLine(\"Hello Git\"); }" 
"// This is HelloITI class"
    "}"
